[platformio]
src_dir = .
include_dir = app/inc

[env:bluepill_f103c8]
platform = ststm32
board = bluepill_f103c8
framework = stm32cube

build_src_filter =
  -<*>
  +<app/src/>
  +<middle/usb/src/>

build_flags =
  -Iapp/inc
  -Imiddle/usb/inc
  -DUSE_HAL_DRIVER
  -DSTM32F103xB
