[platformio]
src_dir = .
include_dir = Core/Inc
default_envs = production

[env:genericSTM32F103C8]
platform = ststm32
board = genericSTM32F103C8
framework = stm32cube
upload_protocol = jlink
debug_speed = 4000
upload_flags =
  -ExitOnError
  1

build_src_filter =
  -<*>
  +<Core/Src/>

build_flags =
  -ICore/Inc
  -DUSE_HAL_DRIVER
  -DSTM32F103xB
  -Wl,-u,_printf_float

[env:production]
extends = env:genericSTM32F103C8
build_flags =
  ${env:genericSTM32F103C8.build_flags}
  -DACTIVE_MODE=MODE_NORMAL
  -DADS7861_USE_BITBANG_BRINGUP=0
  -DADS7861_RELAX_FRAME_VALIDATION=0

[env:usb_cdc_test]
extends = env:genericSTM32F103C8
build_flags =
  ${env:genericSTM32F103C8.build_flags}
  -DACTIVE_MODE=MODE_TEST_USB

[env:mcp4822_test]
extends = env:genericSTM32F103C8
build_flags =
  ${env:genericSTM32F103C8.build_flags}
  -DACTIVE_MODE=MODE_TEST_DAC
