[platformio]
src_dir = .
include_dir = Core/Inc
default_envs = genericSTM32F103C8

[env:genericSTM32F103C8]
platform = ststm32
board = genericSTM32F103C8
framework = stm32cube
upload_protocol = jlink

build_src_filter =
  -<*>
  +<Core/Src/>

build_flags =
  -ICore/Inc
  -DUSE_HAL_DRIVER
  -DSTM32F103xB

[env:usb_cdc_test]
extends = env:genericSTM32F103C8
build_flags =
  ${env:genericSTM32F103C8.build_flags}
  -DACTIVE_MODE=MODE_TEST_USB

